### ISSUE TITLE
Propane Tank Monitor - add

### ISSUE THREAD

**Issue by tgarrison3** [binarydev/ha-generac#15]
Here's my marked up JSON showing my propane tank monitor with comments (tagged #ted#) about what some values are:

[
   {
      "#ted#":" this is all generator related",
      "apparatusId":1110300,
      "serialNumber":"11111111",
      "name":"Genny",
      "type":0,
      "localizedAddress":"3 some Road, binghamton, NY, 13901",
      "materialDescription":null,
      "heroImageUrl":"https://soa.generac.com/selfhelp/media/6af4702c-b653-4abb-988d-efc4e67c2413",
      "apparatusStatus":1,
      "isConnected":true,
      "isConnecting":false,
      "showWarning":false,
      "weather":{
         "temperature":{
            "value":24,
            "unit":"F",
            "unitType":18
         },
         "iconCode":33
      },
      "preferredDealerName":"DJK ELECTRIC",
      "preferredDealerPhone":"6077270086",
      "preferredDealerEmail":"djkelectric79@gmail.com",
      "isDealerManaged":false,
      "isDealerUnmonitored":false,
      "modelNumber":"G0072910",
      "panelId":"21",
      "properties":[
         {
            "name":"Subscriptions/apparatuses/1110300/SubscriptionsPremium",
            "value":{
               "type":2,
               "status":1,
               "isLegacy":false,
               "isDunning":false
            },
            "type":2
         },
         {
            "name":"Device",
            "value":{
               "deviceId":"4dc263e2-4661-4c99-91be-957dbe325a5f",
               "deviceType":"wifi",
               "signalStrength":"14%",
               "batteryLevel":null,
               "status":"Online",
               "networkType":"wifi"
            },
            "type":3
         }
      ],
      "values":null,
      "provisioned":"2023-11-06T22:15:34.628313Z"
   },
   {
      "#ted#":"” this is the propane monitor”",
      "apparatusId":1135681,
      "serialNumber":null,
      "#ted#":"”this is the name i gave the tank in the app”",
      "name":"500",
      "type":2,
      "localizedAddress":"3 some Road, binghamton, NY, 13901",
      "materialDescription":null,
      "heroImageUrl":null,
      "apparatusStatus":0,
      "isConnected":true,
      "isConnecting":false,
      "showWarning":false,
      "weather":null,
      "preferredDealerName":null,
      "preferredDealerPhone":null,
      "preferredDealerEmail":null,
      "isDealerManaged":false,
      "isDealerUnmonitored":false,
      "modelNumber":null,
      "panelId":null,
      "properties":[
         {
            "name":"Subscriptions/apparatuses/1135681/SubscriptionsPremium",
            "value":{
               "type":2,
               "status":1,
               "isLegacy":false,
               "isDunning":false
            },
            "type":2
         },
         {
            "name":"Device",
            "value":{
               "deviceId":"002c00123036323316473134",
               "deviceType":"lte-tankutility-v2",
               "signalStrength":null,
               "#ted#":"”batteryLevel and status both appear accurate”",
               "batteryLevel":"good",
               "status":"Online",
               "networkType":"lte-tankutility-v2"
            },
            "type":3
         },
         {
            "#ted#":"” this is accurate”",
            "name":"FuelType",
            "value":"Propane",
            "type":0
         },
         {
            "#ted#":"” this is accurate”",
            "name":"Orientation",
            "value":"horizontal",
            "type":0
         },
         {
            "#ted#":"” this is accurate”",
            "name":"Capacity",
            "value":"500",
            "type":0
         },
         {
            "#ted#":"” this is accurate”",
            "name":"ConsumptionTypes",
            "value":null,
            "type":0
         },
         {
            "#ted#":"” guess this is accurate - i’m guessing the value translates somewhere else in their system”",
            "name":"FuelDealerId",
            "value":"-MTlVxCs0HvpbVcoa1_E",
            "type":0
         },
         {
            "#ted#":"” this is accurate”",
            "name":"LastReading",
            "value":"2023-12-21T15:47:23Z",
            "type":0
         },
         {
            "#ted#":"” this is accurate”",
            "name":"FuelLevel",
            "#ted#":”this is 74%”,
            "value":74,
            "type":0
         }
      ],
      "values":null,
      "#ted#":"” this must be when it was built. It’s not when I activated it”",
      "provisioned":"2022-08-14T19:06:58.8861501Z"
   }
]

**Comment by binarydev** [comment]
Now that i'm done with v0.1.2 which makes the polling interval configurable, I'll move on to working on adding this in. Thanks for the JSON example!

**Comment by binarydev** [comment]
@tgarrison3 the JSON you shared seems to be for the device list API endpoint (/v2/Apparatus/list). Do you mind sharing the JSON response for the device details GET (/v1/Apparatus/details/1135681)? That'll provide the missing link I need to complete the model schema and wrap this up. Other than that, I already have the propane monitor appearing in the UI based on your earlier JSON, but it can't populate all of the relevant entity fields without the device details.

**Comment by binarydev** [comment]
Actually @tgarrison3 if you can, clone this repo locally, run `pip install -r requirements.txt` and `GENERAC_USER="your@email.com" GENERAC_PASS="your-password" python local_test.py` (you may need to replace `python local_test.py` with `python3 local_test.py` depending on your system's setup).

The output from that local test script should give me everything I need to work with. Thanks!

**Comment by tgarrison3** [comment]
Used the API for now to get it - I'm not setup to clone the repo currently - rebuilding my machine.

{
"apparatusId": 1135681,
"name": "the pig",
"serialNumber": null,
"apparatusClassification": 2,
"panelId": null,
"activationDate": null,
"deviceType": "lte-tankutility-v2",
"deviceSsid": null,
"shortDeviceId": "RXCPGNQG",
"networkType": null,
"apparatusStatus": 0,
"heroImageUrl": null,
"statusLabel": null,
"statusText": null,
"eCodeLabel": null,
"weather": null,
"isConnected": true,
"isConnecting": false,
"showWarning": false,
"hasMaintenanceAlert": false,
"lastSeen": null,
"connectionTimestamp": null,
"address": {
"line1": "5 Some Road",
"line2": null,
"city": "Binghamton",
"region": "NY",
"country": "US",
"postalCode": "13778"
},
"properties": [],
"tuProperties": [
{
"name": null,
"value": 73,
"type": 9
},
{
"name": null,
"value": "2023-12-24T15:48:54Z",
"type": 11
},
{
"name": null,
"value": "-1",
"type": 7
},
{
"name": "Propane",
"value": "Propane",
"type": 0
},
{
"name": "1.6.2.2.3",
"value": "horizontal",
"type": 2
},
{
"name": "1.6.2.2.2",
"value": "500",
"type": 1
},
{
"name": "1.6.2.2.4",
"value": "",
"type": 3
},
{
"name": "1.6.2.2.11",
"value": "-MTlVxCs0HvpbVcoa1_E",
"type": 13
},
{
"name": null,
"value": "good",
"type": 17
}
],
"subscription": {
"type": 2,
"status": 1,
"isLegacy": false,
"isDunning": false
},
"enrolledInVpp": false,
"hasActiveVppEvent": false,
"productInfo": [],
"disconnectedNotification": null,
"hasDisconnectedNotificationsOn": false
}

**Comment by binarydev** [comment]
thanks for the output @tgarrison3! Can you clarify if the name of your device is "500" or "the pig"? The device detail says the latter, but your annotated device listing JSON in comment 1 says that "500" is the name. I just want to make sure I line up the fields correctly here.

**Comment by tgarrison3** [comment]
Both.  It was "500", but I renamed it "the pig" when I wanted to verify
what the field was.  So both JSONs are correct, but the details one is
current.

**Comment by binarydev** [comment]
Awesome, then I think I have a version of the integration ready for you to test! It works well with the json you gave me as inputs but now it's ready for real world testing. I just need to figure out how to configure beta releases for HACS integrations, and then I'll follow up here. Should be hearing from me again later today for the greenlight to try it out!

**Comment by tgarrison3** [comment]
I'm not on hacs currently, so I just grab the custom components folder from
GitHub and bring it in manually.

**Comment by binarydev** [comment]
@tgarrison3 Even better, grab the latest files from this branch and give it a shot: https://github.com/binarydev/ha-generac/tree/add_propane_monitor

I've linked my WIP PR to this issue, and if all works well for you I'll merge the code into the main branch and cut a new release for everyone else to update.

**Comment by tgarrison3** [comment]
Looks good so far on my end.  I'll keep an eye on it (propane monitor only
submits a reading every 24hrs) and let you know how it looks after
tommorows update.

**Comment by binarydev** [comment]
Sorry didn't mean to close this when I merged the PR. Reopening until you can confirm tomorrow that the 24h update was successful @tgarrison3. This feature is now released in v0.2 on the main branch. There are no changes from the copy you're already testing, so no need for you to pull the update. Feel free to mark this issue as closed if all looks solid after your 24h update!

**Comment by tgarrison3** [comment]
Looks good!  Closing.
