### ISSUE TITLE
connection_time unavailable

### ISSUE THREAD

**Issue by mikesalz** [binarydev/ha-generac#17]
Upgraded to this fork today.  Everything seems to be working well so far, but the connection_time sensor is unavailable.

The log errors below might be related, as they seem to pertain to a time issue.

> 
> Logger: homeassistant
> Source: custom_components/generac/sensor.py:232
> Integration: Generac Generators ([documentation](https://github.com/binarydev/ha-generac), [issues](https://github.com/binarydev/ha-generac/issues))
> First occurred: 4:15:19 PM (505 occurrences)
> Last logged: 8:42:49 PM
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
>     await self._async_refresh(log_failures=True, scheduled=True)
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
>     self.async_update_listeners()
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
>     update_callback()
>   File "/config/custom_components/generac/entity.py", line 83, in _handle_coordinator_update
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
>     state, attr = self._async_generate_attributes()
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
>     value = self.native_value
>             ^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/generac/sensor.py", line 232, in native_value
>     return datetime.strptime(
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
>     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
>     raise ValueError("time data %r does not match format %r" %
> ValueError: time data '2023-04-10T12:50:16.94+00:00' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by mikesalz** [comment]
This was in the log as well.  Similar, but slightly different.

> 
> Logger: homeassistant.components.sensor
> Source: helpers/entity_platform.py:509
> Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> First occurred: 4:14:48 PM (2 occurrences)
> Last logged: 4:18:41 PM
> 
> Error adding entities for domain sensor with platform generac
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
>     await asyncio.gather(*tasks)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
>     await entity.add_to_platform_finish()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
>     state, attr = self._async_generate_attributes()
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
>     value = self.native_value
>             ^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/generac/sensor.py", line 232, in native_value
>     return datetime.strptime(
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
>     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
>                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
>     raise ValueError("time data %r does not match format %r" %
> ValueError: time data '2023-04-10T12:50:16.94+00:00' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by binarydev** [comment]
Fix made and published in v0.1 release. Should appear for you in HACS as an available update to be applied. Remember to restart after updating!
