### ISSUE TITLE
Internal Error on Login - Initial Home Assistant Setup

### ISSUE THREAD

**Issue by doobes** [binarydev/ha-generac#61]
Hi,

I came here from [https://github.com/bentekkie/ha-generac/issues/83](url) after experiencing the error.

I followed the HACS install instructions when adding the integration I get this:

![error](https://github.com/binarydev/ha-generac/assets/23409761/8512c03c-73f5-4a23-90c1-5069f1351649)

Help!

```

**Comment by doobes** [comment]
I'm seemingly the only person with this issue.....

**Comment by binarydev** [comment]
Hey @doobes, sorry for the delay in responding. I didn't see any notifications about this issue. I only noticed it once I was @ mentioned in the other thread by bikeidaho who did get this working following your last comment. I haven't gotten this error report from anyone else, and it's still working for me as well.

Are you able to grab the debug logs in HA for me to take a closer look?

**Comment by doobes** [comment]
No worries. I'm in the middle of a rewire project in my comms closet at present. I'll get the logs for you later today or this evening. Thanks--Christopher Dubea215 Danesbury ParkWilliamsburg, VA 23188Cell: (504) ***@***.*** Apr 16, 2024 11:55 AM, Jose Santiago ***@***.***> wrote:
Hey @doobes, sorry for the delay in responding. I didn't see any notifications about this issue. I only noticed it once I was @ mentioned in the other thread by bikeidaho who did get this working following your last comment. I haven't gotten this error report from anyone else, and it's still working for me as well.
Are you able to grab the debug logs in HA for me to take a closer look?

**Comment by doobes** [comment]
OK.

Um, where do I find the logs you want?

**Comment by binarydev** [comment]
If you go to the integration's page (where it lets you add a new configuration) in your HA, there should be a button in the left hand sidebar to enable debugging. Once you do that the logs (Settings -> System -> Logs) should have DEBUG entries for the Generac integration with some additional details including the error message and line number.

**Comment by binarydev** [comment]
Ah right since you never get it loaded you can't debug. Okay let me try to push an update later tonight after work that provides a more helpful message about what went wrong then and I'll circle back. Once I push the version, you'd have to go to HACS and update the version you have installed locally, then attempt to add the integration to authenticate again.

**Comment by doobes** [comment]
Thank you.

Sorry to be a pain.

**Comment by binarydev** [comment]
Nah no worries. Solving problems is why we're engineers to begin with :)

**Comment by binarydev** [comment]
Just making sure you know that I didn't forget about you! In the little spare time that I've had the last couple of days I've been trying to figure out how I can make it so that you can add the integration without providing credentials up front, to then allow you to enable debugging mode and attempt a login afterward. Will ping you once that's ready!

**Comment by binarydev** [comment]
If there's any chance you would be willing to provide me with your login via a private message/email (preferably using a temporary password on your end, so you can change it when we're done), I can debug this much more easily. Also totally understand if you're not comfortable with that, just thought it'd be worth asking to make things simpler. Alternatively, if you're technical and comfortable installing+running Python, there's a test script you can run in the source code of this repo that lets you validate whether your credentials work and can return device info. That's basically what i would be using to confirm your credentials on my end too.

**Comment by doobes** [comment]
Let's start off with the python script.

I've looked through the files.  I'm guessing it's diagnostics.py?

If I run that I get this:

![image](https://github.com/binarydev/ha-generac/assets/23409761/b6635e88-5e64-4c6e-b678-720f41398587)

Sorry for the screen grab, the terminal daemon in HASS won't let me copy text.

Thanks again

**Comment by binarydev** [comment]
No worries, before you can run the python script you'll need to run `pip install -r requirements.txt` to install some required packages that Python needs to run it properly.

So you would need to run the following:
1.) `pip install -r requirements.txt`
2.) `GENERAC_USER=you@email.com GENERAC_PASS=mypassword python ./local_test.py`

If your credentials are valid, it should show you a bunch of JSON output with your device's info (serial #, "apparatusId", your address, etc.). But if your credentials are invalid/not what they expect, then it'll return this, with the last line being the key indicator:

```
[binarydev:~/Projects/ha-generac]$ GENERAC_USER=you@email.com GENERAC_PASS=mypassword python ./local_test.py                                                                                                 (main✱)
DEBUG:asyncio:Using selector: KqueueSelector
INFO:custom_components.generac:Could not load login page
Traceback (most recent call last):
  File "/Users/binarydev/Projects/ha-generac/./local_test.py", line 32, in <module>
    loop.run_until_complete(main())
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/binarydev/Projects/ha-generac/./local_test.py", line 27, in main
    await api.login()
  File "/Users/binarydev/Projects/ha-generac/custom_components/generac/api.py", line 162, in login
    raise InvalidCredentialsException()
custom_components.generac.api.InvalidCredentialsException
```

You can ignore this warning in the output: `INFO:custom_components.generac:Could not load login page`

**Comment by binarydev** [comment]
It's also worth noting that the credentials you want to use should be the same credentials that work on the official Generac app and website here: https://app.mobilelinkgen.com

**Comment by doobes** [comment]
Running "pip install -r requirements.txt" from the homeassistant/custom_components/generac folder, I'm told:

ERROR: Could not open requirements file: [Error 2] No such file or directory: 'requirements.txt'

I just did a check on my creds.  I was able log off of and back into my account so the creds are valid.

cheers,

**Comment by binarydev** [comment]
Sorry I should have clarified that these are meant to be run in the root of this repo, not in the custom components folder. So you'd have to clone this repo from github to your local machine, then run those commands. In the root of this repo, you'll find the requirements.txt and local_test.py files used by the commands.

**Comment by binarydev** [comment]
Also since your credentials are working as expected, that makes me even more suspicious that the data being returned by the Mobilegen service doesn't match what the code is expecting (maybe a field is blank when it shouldn't be or something). That makes the output of that local_test script above critical to debugging this.

**Comment by doobes** [comment]
OK,

We're past my level of expertise.  I sent you an e-mail.

**Comment by doobes** [comment]
Tried again today. Still not resolved

**Comment by mdisabato** [comment]
I found this integration yesterday and it loaded without a problem. (Sorry @doobes). I also know that HA, for all its stability, sometimes gets a bit wonky. At that point, I do a brute force thing you might want to try:
1 - Remove the integration from HACS. That's the three dots at the right of the HACS entry or at the top right of the description page. 
2 - Delete the custom repository. 
3 - Restart Home Assistant (not reboot, restart)
4 - Reboot Home Assistant (I never figured out why a reboot sometimes needs a restart to fix things.)
5 - Add the custom repository back into HACS.
6 - Reinstall the integration from HACS.  

Did I mention this was brute force? :)

Good luck!

Michael

**Comment by doobes** [comment]
Hey Michael,

Thanks for the response.

I went through the procedure exactly as advised. This is what returns:

![image](https://github.com/binarydev/ha-generac/assets/23409761/83a25ab6-cffb-40e5-836b-67c9934f3b4c)

At this point I'm just going to cry uncle.  There is something in my system that's a bit wonkers, and I don't have the expertise to track it down.

Greatly appreciate your assistance.

**Comment by mdisabato** [comment]
There is a HACS addin called Spook. That might be able to clear up any orphan entries that are causing the issue. Since it might delete stuff you want to keep, do a FULL backup before you use it. 

Michael

**Comment by doobes** [comment]
I even got a wild hair this morning and tried this from a message above:

pip install -r requirements.txt
GENERAC_USER=you@email.com GENERAC_PASS=mypassword python ./local_test.py

I get exactly what Jose predicted➜  

➜  ha-generac-main GENERAC_USER=XXXX GENERAC_PASS=xxxx  python ./local_test.py                                                                                                                                     
DEBUG:asyncio:Using selector: EpollSelector
INFO:custom_components.generac:Could not load login page
Traceback (most recent call last):
  File "/homeassistant/ha-generac-main/./local_test.py", line 32, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/homeassistant/ha-generac-main/./local_test.py", line 27, in main
    await api.login()
  File "/homeassistant/ha-generac-main/custom_components/generac/api.py", line 162, in login
    raise InvalidCredentialsException()
custom_components.generac.api.InvalidCredentialsException

The login creds I supplied are correct.

At this point, I'm out of my league.

Thanks to all who assisted.

**Comment by doobes** [comment]
Truth be told, the Generac/MobileLink people and I are working through some issues.

As many of these devices exhibit, there are a lot of shortcomings in the user front end when it comes to actually managing your info. My experiences with IntelliFire have not exact been bathed in glory either.

When I went to set up MobileLink for my Generac, the first time though the effort did not display the setup.  I guess it's slow being registered.

So I did it again. Unfortunately to realize the original effort had work, with some caveats. The first being that I fat fingered the S/N. It's one digit off.  Unfortunately they give the user no tools whatsoever to manage this other than deleting the account, which I'm on the verge of....

The secondary issue is I have this incomplete setup looming in the app and on their website.

So, I'll work through this with them and then see if I can get the integration to work.

cheers

**Comment by doobes** [comment]
Hooray!

Got the system configured properly on their end and Voila! it works!

Close the ticket....

**Comment by Kurtyou** [comment]
@doobes  On the off chance you remember anything about your issues I'm having the same problem. I was able to get the app set up and working no problem and I doubled checked the serial number, which seemed to be an issue for you. I seem to be fully setup in the app/website as well. Any other insights?
